[project]
name = "fofa-mcp-server"
version = "0.1.0"
description = "A server for querying FOFA API using MCP"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.0",
]
